-- CreateTable
CREATE TABLE "Meeting" (
    "id" SERIAL NOT NULL,
    "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "nCon" INTEGER NOT NULL DEFAULT 0,
    "nPar" INTEGER NOT NULL DEFAULT 0,
    "nStar" INTEGER NOT NULL DEFAULT 0,
    "nIcc" INTEGER NOT NULL DEFAULT 0,
    "nNIcc" INTEGER NOT NULL DEFAULT 0,
    "nNew" INTEGER NOT NULL DEFAULT 0,
    "giId" INTEGER,
    "createAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3),

    CONSTRAINT "Meeting_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Meeting" ADD CONSTRAINT "Meeting_giId_fkey" FOREIGN KEY ("giId") REFERENCES "Gi"("id") ON DELETE SET NULL ON UPDATE CASCADE;
